package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.GUNNJORN, x = 2548, z = 3568, walkRadius = 5, direction = Direction.WEST)

