package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.MUSICIAN_8705, x = 2849, z = 3439, walkRadius = 0, direction = Direction.SOUTH )
spawn_npc(npc = Npcs.BANKER_CLASSIC_MALE_GREY_494, x = 2807, z = 3443, walkRadius = 0, direction = Direction.SOUTH )
spawn_npc(npc = Npcs.BANKER_CLASSIC_FEMALE_GREY_495, x = 2809, z = 3443, walkRadius = 0, direction = Direction.SOUTH )
spawn_npc(npc = Npcs.BANKER_CLASSIC_MALE_GREY_494, x = 2810, z = 3443, walkRadius = 0, direction = Direction.SOUTH )
spawn_npc(npc = Npcs.BANKER_CLASSIC_FEMALE_GREY_495, x = 2811, z = 3443, walkRadius = 0, direction = Direction.SOUTH )
spawn_npc(npc = Npcs.VANESSA, x = 2820, z = 3460, walkRadius = 1, direction = Direction.WEST)
spawn_npc(npc = Npcs.UNICORN, x = 2783, z = 3463, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.MAN, x = 2804, z = 3427, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.ARHEIN, x = 2803, z = 3430, walkRadius = 2, direction = Direction.SOUTH)
//spawn_npc(npc = Npcs.TRADER_CREWMEMBER_4653, x = 2794, z = 3414, walkRadius = 2, direction = Direction.SOUTH)
//spawn_npc(npc = Npcs.TRADER_CREWMEMBER_4656, x = 2795, z = 3414, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.HICKTON, x = 2821, z = 3442, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.HARRY, x = 2836, z = 3447, walkRadius = 2, direction = Direction.EAST)
spawn_npc(npc = Npcs.MAN_3, x = 2818, z = 3443, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.WOMAN_BRUNETTE_PONYTAIL_5, x = 2817, z = 3447, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.FISHERMAN, x = 2853, z = 3429, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.MYSTERIOUS_MAGE, x = 2798, z = 3432, walkRadius = 5, direction = Direction.SOUTH_WEST)

//Fishing Spots
spawn_npc(npc = Npcs.FISHING_SPOT_CAGE_HARPOON, x = 2860, z = 3426, direction = Direction.NORTH, static = true)
spawn_npc(npc = Npcs.FISHING_SPOT_NET_HARPOON, x = 2853, z = 3423, direction = Direction.NORTH, static = true)
spawn_npc(npc = Npcs.FISHING_SPOT_NET_BAIT, x = 2837, z = 3431, direction = Direction.NORTH, static = true)
spawn_npc(npc = Npcs.FISHING_SPOT_NET_BAIT, x = 2855, z = 3423, direction = Direction.NORTH, static = true)
spawn_npc(npc = Npcs.FISHING_SPOT_CAGE_HARPOON, x = 2845, z = 3429, direction = Direction.SOUTH, static = true)