package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.NED, x = 3791, z = 3559, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GREEN_DRAGON, x = 3787, z = 3550, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREEN_DRAGON, x = 3791, z = 3555, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREEN_DRAGON, x = 3794, z = 3550, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREEN_DRAGON, x = 3798, z = 3554, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREEN_DRAGON, x = 3800, z = 3551, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLUE_DRAGON, x = 3809, z = 3551, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLUE_DRAGON, x = 3814, z = 3550, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLUE_DRAGON, x = 3818, z = 3547, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLUE_DRAGON, x = 3822, z = 3551, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLUE_DRAGON, x = 3816, z = 3553, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.RED_DRAGON, x = 3812, z = 3559, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.RED_DRAGON, x = 3810, z = 3565, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.RED_DRAGON, x = 3814, z = 3570, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.RED_DRAGON, x = 3817, z = 3564, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.RED_DRAGON, x = 3822, z = 3562, walkRadius = 5, direction = Direction.NORTH)