package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.ICE_WARRIOR, x = 2861, z = 9920, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 2866, z = 9922, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 2864, z = 9926, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 2867, z = 9929, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.ICE_GIANT, x = 2869, z = 9935, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.ICE_GIANT, x = 2866, z = 9936, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ICE_GIANT, x = 2862, z = 9940, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ICE_GIANT, x = 2872, z = 9941, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.ICE_GIANT, x = 2867, z = 9942, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ICE_SPIDER, x = 2870, z = 9948, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.ICE_SPIDER, x = 2866, z = 9950, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ICE_SPIDER, x = 2861, z = 9952, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ICE_SPIDER, x = 2859, z = 9957, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ICE_SPIDER, x = 2863, z = 9961, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.ICE_SPIDER, x = 2869, z = 9961, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.ICE_SPIDER, x = 2874, z = 9957, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ICE_SPIDER, x = 2871, z = 9954, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.ICE_QUEEN, x = 2865, z = 9956, walkRadius = 5, direction = Direction.SOUTH)
