package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.BLACK_DRAGON, x = 3029, z = 10250, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_DRAGON, x = 3034, z = 10260, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_DRAGON, x = 3040, z = 10255, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_DRAGON, x = 3039, z = 10247, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_DRAGON, x = 3050, z = 10256, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.KING_BLACK_DRAGON, x = 3053, z = 10272, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BRUTAL_GREEN_DRAGON, x = 3066, z = 10254, walkRadius = 5, direction = Direction.SOUTH)
