package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.BATTLE_MAGE_913, x = 3102, z = 3936, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BATTLE_MAGE, x = 3100, z = 3938, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BATTLE_MAGE_914, x = 3098, z = 3940, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BATTLE_MAGE_913, x = 3103, z = 3930, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.BATTLE_MAGE, x = 3101, z = 3927, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.BATTLE_MAGE_914, x = 3099, z = 3925, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.BATTLE_MAGE_913, x = 3108, z = 3933, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.BATTLE_MAGE, x = 3111, z = 3933, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.BATTLE_MAGE_914, x = 3114, z = 3933, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.KOLODION_907, x = 3105, z = 3933, walkRadius = 5, direction = Direction.EAST)

spawn_npc(npc = Npcs.KOLODION, x = 2541, z = 4716, walkRadius = 3, direction = Direction.WEST)
spawn_npc(npc = Npcs.GUNDAI, x = 2534, z = 4713, walkRadius = 3, direction = Direction.WEST)
spawn_npc(npc = Npcs.LUNDAIL, x = 2535, z = 4719, direction = Direction.SOUTH)

spawn_npc(npc = Npcs.CHAMBER_GUARDIAN, x = 2507, z = 4697, walkRadius = 5, direction = Direction.SOUTH)

