package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.JEB_4896, x = 2285, z = 4684, walkRadius = 5, direction = Direction.NORTH_WEST)

