package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.BANKER_CLASSIC_FEMALE_GREY_495, x = 2943, z = 4691, walkRadius = 0, direction = Direction.WEST)
spawn_npc(npc = Npcs.MYSTERIOUS_MAGE, x = 2928, z = 4691, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.ELKOY, x = 2933, z = 4685, walkRadius = 5, direction = Direction.WEST)

