package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.SKELETON_93, x = 2884, z = 9807, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.SKELETON_93, x = 2885, z = 9811, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.SKELETON_93, x = 2882, z = 9814, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.SKELETON_93, x = 2886, z = 9819, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.SKELETON_93, x = 2882, z = 9823, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.SKELETON_93, x = 2885, z = 9828, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.SKELETON_93, x = 2882, z = 9833, walkRadius = 5, direction = Direction.NORTH_WEST)

spawn_npc(npc = Npcs.GHOST_4387, x = 2888, z = 9846, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2891, z = 9848, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2897, z = 9849, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2902, z = 9849, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2908, z = 9849, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2914, z = 9850, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2921, z = 9849, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2935, z = 9836, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2937, z = 9833, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2936, z = 9828, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2930, z = 9823, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GHOST_4387, x = 2916, z = 9819, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2910, z = 9819, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2903, z = 9820, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GHOST_4387, x = 2895, z = 9822, walkRadius = 5, direction = Direction.NORTH_WEST)

spawn_npc(npc = Npcs.CHAOS_DRUID_WARRIOR, x = 2935, z = 9848, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.CHAOS_DRUID_WARRIOR, x = 2930, z = 9849, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.CHAOS_DRUID_WARRIOR, x = 2931, z = 9846, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.CHAOS_DRUID_WARRIOR, x = 2939, z = 9848, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.CHAOS_DRUID_WARRIOR, x = 2937, z = 9845, walkRadius = 5, direction = Direction.SOUTH_EAST)

spawn_npc(npc = Npcs.ALBINO_BAT, x = 2913, z = 9840, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2913, z = 9836, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2914, z = 9831, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2914, z = 9826, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2908, z = 9829, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2908, z = 9835, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2908, z = 9840, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2903, z = 9837, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2903, z = 9832, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2919, z = 9829, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2925, z = 9830, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.ALBINO_BAT, x = 2921, z = 9837, walkRadius = 5, direction = Direction.NORTH_WEST)

spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2938, z = 9818, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2936, z = 9812, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2941, z = 9808, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2941, z = 9804, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2941, z = 9811, walkRadius = 5, direction = Direction.SOUTH_EAST)

spawn_npc(npc = Npcs.MAGIC_AXE, x = 2955, z = 9793, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2961, z = 9793, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2967, z = 9793, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2967, z = 9788, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2960, z = 9788, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2956, z = 9788, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2955, z = 9784, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2961, z = 9783, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2967, z = 9783, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2967, z = 9778, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2960, z = 9778, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2955, z = 9778, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2956, z = 9773, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2961, z = 9773, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.MAGIC_AXE, x = 2967, z = 9773, walkRadius = 5, direction = Direction.EAST)

spawn_npc(npc = Npcs.POISON_SCORPION, x = 2942, z = 9777, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.POISON_SCORPION, x = 2937, z = 9777, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.POISON_SCORPION, x = 2935, z = 9773, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.POISON_SCORPION, x = 2935, z = 9769, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.POISON_SCORPION, x = 2935, z = 9764, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.POISON_SCORPION, x = 2935, z = 9759, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.POISON_SCORPION, x = 2933, z = 9755, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.POISON_SCORPION, x = 2927, z = 9751, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.POISON_SCORPION, x = 2922, z = 9747, walkRadius = 5, direction = Direction.SOUTH_WEST)

spawn_npc(npc = Npcs.CHAOS_DWARF, x = 2915, z = 9756, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.CHAOS_DWARF, x = 2918, z = 9758, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.CHAOS_DWARF, x = 2919, z = 9756, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.CHAOS_DWARF, x = 2922, z = 9760, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.CHAOS_DWARF, x = 2926, z = 9761, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.CHAOS_DWARF, x = 2926, z = 9767, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.CHAOS_DWARF, x = 2928, z = 9771, walkRadius = 5, direction = Direction.EAST)

spawn_npc(npc = Npcs.LESSER_DEMON, x = 2932, z = 9782, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.LESSER_DEMON, x = 2936, z = 9785, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.LESSER_DEMON, x = 2935, z = 9789, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.LESSER_DEMON, x = 2935, z = 9795, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.LESSER_DEMON, x = 2931, z = 9794, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.LESSER_DEMON, x = 2930, z = 9800, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.LESSER_DEMON, x = 2930, z = 9806, walkRadius = 5, direction = Direction.NORTH)

spawn_npc(npc = Npcs.BABY_BLUE_DRAGON, x = 2916, z = 9806, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BABY_BLUE_DRAGON, x = 2914, z = 9801, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.BABY_BLUE_DRAGON, x = 2906, z = 9802, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.BABY_BLUE_DRAGON, x = 2896, z = 9802, walkRadius = 5, direction = Direction.WEST)

spawn_npc(npc = Npcs.BLUE_DRAGON, x = 2899, z = 9798, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLUE_DRAGON, x = 2904, z = 9807, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.BLUE_DRAGON, x = 2911, z = 9804, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLUE_DRAGON, x = 2920, z = 9803, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.BLUE_DRAGON, x = 2916, z = 9798, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLUE_DRAGON, x = 2905, z = 9796, walkRadius = 5, direction = Direction.SOUTH_WEST)

spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2894, z = 9776, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2896, z = 9771, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2899, z = 9766, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2889, z = 9769, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2882, z = 9768, walkRadius = 5, direction = Direction.SOUTH_WEST)

spawn_npc(npc = Npcs.KALGER_THE_WARMONGER_12800, x = 2855, z = 9776, walkRadius = 5, direction = Direction.SOUTH_WEST)

spawn_npc(npc = Npcs.BLACK_DEMON, x = 2858, z = 9773, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.BLACK_DEMON, x = 2863, z = 9769, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_DEMON, x = 2861, z = 9765, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.BLACK_DEMON, x = 2865, z = 9775, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.BLACK_DEMON, x = 2862, z = 9782, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.BLACK_DEMON, x = 2868, z = 9781, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_DEMON, x = 2875, z = 9784, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.BLACK_DEMON, x = 2874, z = 9777, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2871, z = 9798, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2877, z = 9805, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2871, z = 9812, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2862, z = 9820, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2854, z = 9820, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2849, z = 9816, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2849, z = 9811, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2853, z = 9806, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2861, z = 9813, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2857, z = 9802, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.GREATER_DEMON, x = 2864, z = 9799, walkRadius = 5, direction = Direction.SOUTH_EAST)

spawn_npc(npc = Npcs.MONK_OF_ZAMORAK_1044, x = 2833, z = 9814, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.MONK_OF_ZAMORAK_1044, x = 2827, z = 9813, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.MONK_OF_ZAMORAK_1044, x = 2827, z = 9809, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.MONK_OF_ZAMORAK_1044, x = 2830, z = 9808, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.MONK_OF_ZAMORAK_1044, x = 2832, z = 9811, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.MONK_OF_ZAMORAK_1044, x = 2828, z = 9804, walkRadius = 5, direction = Direction.SOUTH_WEST)

spawn_npc(npc = Npcs.BLACK_DRAGON, x = 2827, z = 9826, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.BLACK_DRAGON, x = 2835, z = 9826, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.BLACK_DRAGON, x = 2845, z = 9824, walkRadius = 5, direction = Direction.SOUTH_EAST)

spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2854, z = 9833, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2859, z = 9837, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2861, z = 9842, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2856, z = 9840, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2858, z = 9846, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2855, z = 9850, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2862, z = 9851, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2866, z = 9849, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2872, z = 9848, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2870, z = 9844, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2868, z = 9840, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2870, z = 9835, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.SKELETON_HELLHOUND, x = 2869, z = 9830, walkRadius = 5, direction = Direction.SOUTH_WEST)

spawn_npc(npc = Npcs.GIANT_SKELETON, x = 2909, z = 9739, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.GIANT_SKELETON, x = 2904, z = 9737, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.GIANT_SKELETON, x = 2904, z = 9732, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GIANT_SKELETON, x = 2904, z = 9727, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GIANT_SKELETON, x = 2910, z = 9726, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.GIANT_SKELETON, x = 2913, z = 9731, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GIANT_SKELETON, x = 2911, z = 9735, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GIANT_SKELETON, x = 2907, z = 9731, walkRadius = 5, direction = Direction.SOUTH_WEST)

spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2900, z = 9711, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2907, z = 9711, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2915, z = 9711, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2915, z = 9706, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2907, z = 9706, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2899, z = 9706, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2907, z = 9701, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.BLACK_KNIGHT_6189, x = 2915, z = 9701, walkRadius = 5, direction = Direction.EAST)

spawn_npc(npc = Npcs.ELITE_BLACK_KNIGHT, x = 2911, z = 9692, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.ELITE_BLACK_KNIGHT, x = 2905, z = 9692, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.ELITE_BLACK_KNIGHT, x = 2906, z = 9686, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.ELITE_BLACK_KNIGHT, x = 2912, z = 9682, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.ELITE_BLACK_KNIGHT, x = 2911, z = 9677, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.ELITE_BLACK_KNIGHT, x = 2905, z = 9674, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.ELITE_BLACK_KNIGHT, x = 2900, z = 9680, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ELITE_BLACK_KNIGHT, x = 2898, z = 9688, walkRadius = 5, direction = Direction.NORTH_WEST)

spawn_npc(npc = Npcs.ELITE_BLACK_KNIGHT_8330, x = 2907, z = 9699, walkRadius = 0, direction = Direction.NORTH)