package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.ELKOY, x = 2460, z = 3414, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.MYSTERIOUS_MAGE, x = 2461, z = 3425, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.GNOME_TRAINER, x = 2479, z = 3427, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.GNOME_COACH, x = 2475, z = 3438, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.GNOME_BANKER, x = 2448, z = 3427, height = 1, walkRadius = 0, direction = Direction.WEST)
spawn_npc(npc = Npcs.GNOME_BANKER, x = 2448, z = 3424, height = 1, walkRadius = 0, direction = Direction.WEST)
spawn_npc(npc = Npcs.GNOME_BANKER, x = 2443, z = 3424, height = 1, walkRadius = 0, direction = Direction.EAST)
spawn_npc(npc = Npcs.GNOME_BANKER, x = 2443, z = 3425, height = 1, walkRadius = 0, direction = Direction.EAST)

spawn_npc(npc = Npcs.GNOME_GUARD, x = 2458, z = 3389, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GNOME_GUARD_164, x = 2463, z = 3389, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.GNOME_GUARD, x = 2462, z = 3393, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GNOME_GUARD_164, x = 2458, z = 3395, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GNOME_GUARD, x = 2459, z = 3399, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GNOME_GUARD_164, x = 2462, z = 3399, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.GNOME_GUARD, x = 2460, z = 3395, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.GNOME_GUARD_164, x = 2461, z = 3390, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.GNOME_GUARD, x = 2461, z = 3385, walkRadius = 5, direction = Direction.SOUTH)

spawn_npc(npc = Npcs.GNOME_WOMAN, x = 2475, z = 3404, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GNOME_CHILD, x = 2474, z = 3408, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GNOME_2249, x = 2488, z = 3404, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.GNOME_2251, x = 2486, z = 3406, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GNOME_WOMAN_169, x = 2480, z = 3406, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.GNOME_CHILD_161, x = 2473, z = 3407, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.GNOME_WOMAN, x = 2476, z = 3399, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.GNOME_CHILD, x = 2457, z = 3410, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GNOME_CHILD_160, x = 2459, z = 3414, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GNOME_CHILD_161, x = 2461, z = 3410, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.GNOME_WOMAN_169, x = 2459, z = 3412, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GNOME_2249, x = 2459, z = 3432, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GNOME_2251, x = 2462, z = 3434, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GNOME_2249, x = 2459, z = 3437, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GNOME_2251, x = 2461, z = 3439, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GNOME_CHILD, x = 2440, z = 3444, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.GNOME_CHILD_160, x = 2441, z = 3449, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GNOME_CHILD_161, x = 2444, z = 3447, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.GNOME_WOMAN, x = 2444, z = 3444, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GNOME_WOMAN_169, x = 2440, z = 3447, walkRadius = 5, direction = Direction.NORTH_WEST)
