package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.ELKOY, x = 2460, z = 3414, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.MYSTERIOUS_MAGE, x = 2461, z = 3425, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.GNOME_TRAINER, x = 2479, z = 3427, walkRadius = 5, direction = Direction.WEST)

