package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.SIR_VANT, x = 3680, z = 4944, walkRadius = 0, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.DRAGON_8858, x = 3680, z = 4947, walkRadius = 5, direction = Direction.SOUTH)
