package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */
spawn_npc(npc = Npcs.MALIGNIUS_MORTIFER, x = 2997, z = 3911, walkRadius = 5, direction = Direction.WEST) //Agility course teleporter