package gg.rsmod.plugins.content.areas.spawns

/**
 * Generated by: Supertje/Eikenoom
 * For Project Harmony
 */

/** NPC's */

spawn_npc(npc = Npcs.BLACK_KNIGHT_TITAN, x = 2564, z = 9507, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.NEZIKCHENED, x = 2571, z = 9528, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.SAN_TOJALON, x = 2614, z = 9522, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.SHADOW_SPIDER, x = 2616, z = 9569, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.SHADOW_SPIDER, x = 2617, z = 9567, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.SHADOW_SPIDER, x = 2618, z = 9565, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.SHADOW_SPIDER, x = 2620, z = 9566, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.SHADOW_SPIDER, x = 2622, z = 9565, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.FIRE_GIANT_1586, x = 2620, z = 9486, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.FIRE_GIANT_1585, x = 2617, z = 9484, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.FIRE_GIANT_1584, x = 2616, z = 9486, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.FIRE_GIANT_1583, x = 2613, z = 9487, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.FIRE_GIANT_1582, x = 2614, z = 9483, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.FIRE_GIANT_1584, x = 2611, z = 9483, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.FIRE_GIANT_1582, x = 2610, z = 9486, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.FIRE_GIANT_1586, x = 2608, z = 9484, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.MUMMY_2015, x = 2594, z = 9498, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.MUMMY_2016, x = 2591, z = 9499, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.MUMMY_2015, x = 2587, z = 9498, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.MUMMY_2016, x = 2585, z = 9500, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.MUMMY_2015, x = 2584, z = 9498, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.MUMMY_2016, x = 2580, z = 9498, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.MUMMY_2015, x = 2577, z = 9499, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.MUMMY_2016, x = 2574, z = 9501, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.MUMMY_2015, x = 2577, z = 9502, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.MUMMY_2016, x = 2580, z = 9501, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.MUMMY_2015, x = 2583, z = 9502, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.GIANT_CRYPT_SPIDER, x = 2576, z = 9524, walkRadius = 8, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GIANT_CRYPT_SPIDER, x = 2576, z = 9528, walkRadius = 8, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GIANT_CRYPT_SPIDER, x = 2574, z = 9531, walkRadius = 8, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GIANT_CRYPT_SPIDER, x = 2570, z = 9531, walkRadius = 8, direction = Direction.WEST)
spawn_npc(npc = Npcs.GIANT_CRYPT_SPIDER, x = 2568, z = 9528, walkRadius = 8, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.GIANT_CRYPT_SPIDER, x = 2570, z = 9526, walkRadius = 8, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.GIANT_CRYPT_SPIDER, x = 2573, z = 9526, walkRadius = 8, direction = Direction.NORTH_WEST)
